#services:
# postgres:
#   image: postgres:latest
#   container_name: postgres-container
#   restart: always
#   environment:
#     - POSTGRES_DB=webshop
#     - POSTGRES_USER=neondb_owner
#     - POSTGRES_PASSWORD=npg_shp7OkutMBZ2
#   ports:
#     - '5432:5432'
#   volumes:
#     - db_data:/var/lib/postgresql/data
#
#volumes:
# db_data:
