services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql-container
    restart: always
    environment:
      - 'MYSQL_DATABASE=localhost_webshop'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'


volumes:
  db_data: